### ISSUE TITLE
Actually work on this

### ISSUE THREAD

**Issue by BastelPichi** [BastelPichi/pyscooter#1]
I swear ill work on this in the next week lol

**Comment by IdotMaster1** [comment]
![bkctroll](https://user-images.githubusercontent.com/48019206/207691443-6bb1dab4-97e0-48ce-9b91-84c671807748.png)

**Comment by BastelPichi** [comment]
bro pls relate?

**Comment by IdotMaster1** [comment]
i wanted to remind you

**Comment by BastelPichi** [comment]
Get banned
